var data = {
  authorName: "xiang.chen",
  tableDesc: "样例服务",
  modulePathArr: ["common", "user"],
  moduleKey: "userModule",
  moduleName: "用户模块",
  searchItems: [
    {
      isKey: 0,
      colName: "demoName",
      colType: "varchar",
      colDesc: "姓名",
      colLength: 200,
      jsType: "string",
      options: "",
      placeholder: "",
      colCNName: "姓名",
    },
    {
      isKey: 0,
      colName: "demoAge",
      colType: "varchar",
      colDesc: "年龄",
      colLength: 200,
      jsType: "string",
      options: "",
      placeholder: "",
      colCNName: "年龄",
    },
    {
      isKey: 0,
      colName: "demoSex",
      colType: "int",
      colDesc: "性别：0 未知，1 男，2 女",
      colLength: null,
      jsType: "number",
      options: "demoSex_options",
      placeholder: "",
      colCNName: "性别",
    },
    {
      isKey: 0,
      colName: "remark",
      colType: "varchar",
      colDesc: "备注",
      colLength: 500,
      jsType: "string",
      options: "",
      placeholder: "",
      colCNName: "备注",
    },
    {
      isKey: 0,
      colName: "createTime",
      colType: "datetime",
      colDesc: "创建时间",
      colLength: null,
      jsType: "date",
      options: "",
      placeholder: "",
      colCNName: "创建时间",
    },
    {
      isKey: 0,
      colName: "deleteFlag",
      colType: "varchar",
      colDesc: "数据删除标记（空字符串表示有效，非空无效）",
      colLength: 50,
      jsType: "string",
      options: "",
      placeholder: "空字符串表示有效，非空无效",
      colCNName: "数据删除标记",
    },
  ],
  tableColumns: [
    {
      isKey: 0,
      colName: "demoName",
      colType: "varchar",
      colDesc: "姓名",
      colLength: 200,
      jsType: "string",
      options: "",
      placeholder: "",
      colCNName: "姓名",
    },
    {
      isKey: 0,
      colName: "demoAge",
      colType: "varchar",
      colDesc: "年龄",
      colLength: 200,
      jsType: "string",
      options: "",
      placeholder: "",
      colCNName: "年龄",
    },
    {
      isKey: 0,
      colName: "demoSex",
      colType: "int",
      colDesc: "性别：0 未知，1 男，2 女",
      colLength: null,
      jsType: "number",
      options: "demoSex_options",
      placeholder: "",
      colCNName: "性别",
    },
    {
      isKey: 0,
      colName: "remark",
      colType: "varchar",
      colDesc: "备注",
      colLength: 500,
      jsType: "string",
      options: "",
      placeholder: "",
      colCNName: "备注",
    },
    {
      isKey: 0,
      colName: "createUser",
      colType: "int",
      colDesc: "创建人",
      colLength: null,
      jsType: "number",
      options: "",
      placeholder: "",
      colCNName: "创建人",
    },
    {
      isKey: 0,
      colName: "createTime",
      colType: "datetime",
      colDesc: "创建时间",
      colLength: null,
      jsType: "date",
      options: "",
      placeholder: "",
      colCNName: "创建时间",
    },
    {
      isKey: 0,
      colName: "deleteFlag",
      colType: "varchar",
      colDesc: "数据删除标记（空字符串表示有效，非空无效）",
      colLength: 50,
      jsType: "string",
      options: "",
      placeholder: "空字符串表示有效，非空无效",
      colCNName: "数据删除标记",
    },
  ],
  formItems: [
    [
      {
        isKey: 0,
        colName: "demoName",
        colType: "varchar",
        colDesc: "姓名",
        colLength: 200,
        rules: ["isNotEmpty"],
        isAllWidth: true,
        jsType: "string",
        options: "",
        placeholder: "",
        colCNName: "姓名",
      },
    ],
    [
      {
        isKey: 0,
        colName: "demoAge",
        colType: "varchar",
        colDesc: "年龄",
        colLength: 200,
        rules: ["isNotEmpty"],
        isAllWidth: true,
        jsType: "string",
        options: "",
        placeholder: "",
        colCNName: "年龄",
      },
    ],
    [
      {
        isKey: 0,
        colName: "demoSex",
        colType: "int",
        colDesc: "性别：0 未知，1 男，2 女",
        colLength: null,
        rules: ["isNotEmpty", "isNumber"],
        isAllWidth: false,
        jsType: "number",
        options: "demoSex_options",
        placeholder: "",
        colCNName: "性别",
      },
      {
        isKey: 0,
        colName: "remark",
        colType: "varchar",
        colDesc: "备注",
        colLength: 500,
        rules: ["isNotEmpty"],
        isAllWidth: false,
        jsType: "string",
        options: "",
        placeholder: "",
        colCNName: "备注",
      },
    ],
    [
      {
        isKey: 0,
        colName: "createUser",
        colType: "int",
        colDesc: "创建人",
        colLength: null,
        rules: ["isNotEmpty"],
        isAllWidth: true,
        jsType: "number",
        options: "",
        placeholder: "",
        colCNName: "创建人",
      },
    ],
    [
      {
        isKey: 0,
        colName: "createTime",
        colType: "datetime",
        colDesc: "创建时间",
        colLength: null,
        rules: ["isNotEmpty"],
        isAllWidth: false,
        jsType: "date",
        options: "",
        placeholder: "",
        colCNName: "创建时间",
      },
    ],
    [
      {
        isKey: 0,
        colName: "lastModifyUser",
        colType: "int",
        colDesc: "修改人",
        colLength: null,
        rules: [],
        isAllWidth: true,
        jsType: "number",
        options: "",
        placeholder: "",
        colCNName: "修改人",
      },
    ],
    [
      {
        isKey: 0,
        colName: "deleteFlag",
        colType: "varchar",
        colDesc: "数据删除标记（空字符串表示有效，非空无效）",
        colLength: 50,
        rules: ["isNotEmpty"],
        isAllWidth: true,
        jsType: "string",
        options: "",
        placeholder: "空字符串表示有效，非空无效",
        colCNName: "数据删除标记",
      },
    ],
  ],
  options: {
    demoSex_options: [
      { name: "未知", value: "0" },
      { name: "男", value: "1" },
      { name: "女", value: "2" },
    ],
    demoSex2_options: [
        { name: "未知", value: "0" },
        { name: "男", value: "1" },
        { name: "女", value: "2" },
      ],
  },
  optionsKeys:["demoSex_options","demoSex2_options"],
  createTime: "2020/11/11 下午4:31:47",
  modulePath: "/common/user",
  ClassName: "BaseDemo",
  className: "baseDemo",
  viewColumnName: "demoName",
  optionButtons: ["编辑", "新增", "删除"],
  selection: true,
};
